flatpak install flathub com.discordapp.Discord -y
flatpak install flathub com.github.IsmaelMartinez.teams_for_linux -y
flatpak install flathub com.github.neithern.g4music -y
flatpak install flathub com.github.unrud.VideoDownloader -y
flatpak install flathub com.mattjakeman.ExtensionManager -y
flatpak install flathub com.raggesilver.BlackBox -y
flatpak install flathub com.skype.Client -y
flatpak install flathub de.haeckerfelix.Fragments -y
flatpak install flathub io.dbeaver.DBeaverCommunity -y
flatpak install flathub io.github.alainm23.planify -y
flatpak install flathub io.github.celluloid_player.Celluloid -y
flatpak install flathub me.ppvan.psequel -y
flatpak install psequel-origin me.ppvan.psequel -y
flatpak install flathub org.freedesktop.appstream-glib -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.gnome.Builder -y
flatpak install flathub org.gnome.design.AppIconPreview -y
flatpak install flathub org.gnome.design.IconLibrary -y
flatpak install flathub org.gnome.meld -y
flatpak install flathub org.inkscape.Inkscape -y
flatpak install flathub re.sonny.Workbench -y
