
[window]
opacity = 0.9
padding.x = 4
padding.y = 4


[font]
size = 12.0
normal.family = "Iosevka Extended"
bold.family = "Iosevka Extended"
italic.family = "Iosevka Extended"
bold_italic.family = "Iosevka Extended"

[general]

import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
